# Generated by Django 3.2.6 on 2022-10-10 11:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminiBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n03_001', models.CharField(max_length=10, verbose_name='都道府県明')),
                ('n03_002', models.CharField(max_length=20, null=True, verbose_name='支庁・振興局名')),
                ('n03_003', models.CharField(max_length=20, null=True, verbose_name='郡・政令都市名')),
                ('n03_004', models.CharField(max_length=20, null=True, verbose_name='市区町村名')),
                ('n03_007', models.CharField(max_length=5, null=True, verbose_name='行政区域コード')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c28_001', models.CharField(max_length=5, verbose_name='行政区域コード')),
                ('c28_003', models.BigIntegerField(verbose_name='種別')),
                ('c28_004', models.CharField(max_length=6, verbose_name='供用中・建設中の区別')),
                ('c28_005', models.CharField(max_length=22, verbose_name='名称')),
                ('c28_006', models.BigIntegerField(verbose_name='設置者')),
                ('c28_007', models.BigIntegerField(verbose_name='管理者')),
                ('c28_008', models.CharField(max_length=126, verbose_name='特定飛行場の指定状況')),
                ('c28_009', models.CharField(max_length=4, verbose_name='運用時間（開始）')),
                ('c28_010', models.CharField(max_length=4, verbose_name='運用時間（終了）')),
                ('c28_011', models.BigIntegerField(verbose_name='定期便の有無')),
                ('c28_012', models.CharField(max_length=19, verbose_name='滑走路延長')),
                ('c28_013', models.CharField(max_length=11, verbose_name='滑走路幅')),
                ('c28_101', models.CharField(blank=True, max_length=11, null=True, verbose_name='標点')),
                ('c28_102', models.CharField(blank=True, max_length=11, null=True, verbose_name='ターミナルビル')),
                ('c28_103', models.CharField(blank=True, max_length=254, null=True, verbose_name='調査内容')),
                ('c28_104', models.CharField(blank=True, max_length=254, null=True, verbose_name='調査内容（続き）')),
                ('c28_000', models.CharField(blank=True, max_length=13, null=True, verbose_name='空港ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
